language: python
cache: pip

python:
  - 2.7
  - 3.5
  - 3.6
  - pypy

# Python 3.7 requires Xenial
matrix:
  include:
    - python: 3.7
      dist: xenial

install:
  - pip install -r requirements-dev.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install -U black; fi

script:
  - nosetests --with-coverage --cover-package=slacker_cli
  - flake8 slacker_cli tests
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then black --check --diff .; fi

after_script:
  - coveralls --verbose
